services:

  # Django application
  simple_crm:
    container_name: cool_carl
    #directory location
    build: .
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    #command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic && gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - db
    ports:
      - 8000:8000
    restart: on-failure
    # healthcheck:
    #   test: [ "CMD", "curl", "-f", "http://localhost:8000" ]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3


  db:
    container_name: cool_carl_db
    image: postgres:15.3-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=carlhubdb
      - POSTGRES_USER=carlhub
      - POSTGRES_PASSWORD=1234
volumes:
  postgres_data:
  static_volume:
  media_volume:

  # nginx:
  #   container_name: nginx
  #   #build directory/folder location 
  #   build: ./nginx
  #   ports:
  #     - "1337:80"
  #   volumes:
  #     - static_volume:/home/static
  #     - media_volume:/home/media
  #   depends_on:
  #   #service name
  #     - simple_crm
  #   restart: on-failure

  # gunicorn:   
  #   container_name: gunicorn
  #   build: .
  #   command: systemctl start carlhub.service    
    
