# Generated by Django 4.2.1 on 2023-07-08 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client_relationship_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='organisation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='client_organisation', to='client_relationship_manager.userprofile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agent',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_organisation', to='client_relationship_manager.userprofile'),
        ),
    ]
